<a href="https://colab.research.google.com/github/bugsotim/INTERNSHIP_CN_2026/blob/main/shopee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
df_2024_1 = pd.read_excel('/content/2024-01-01_2024-01-31.xlsx')
df_2024_2 = pd.read_excel('/content/2024-02-01_2024-02-29.xlsx')
df_2024_3 = pd.read_excel('/content/2024-03-01_2024-03-31.xlsx')
df_2025_1_13 = pd.read_excel('/content/2025-01-01_2025-01-31_part_1_of_3.xlsx')
df_2025_1_23 = pd.read_excel('/content/2025-01-01_2025-01-31_part_2_of_3.xlsx')
df_2025_1_33 = pd.read_excel('/content/2025-01-01_2025-01-31_part_3_of_3.xlsx')
df_2025_2_14 = pd.read_excel('/content/2025-02-01_2025-02-28_part_1_of_4.xlsx')
df_2025_2_24 = pd.read_excel('/content/2025-02-01_2025-02-28_part_2_of_4.xlsx')
df_2025_2_34 = pd.read_excel('/content/2025-02-01_2025-02-28_part_3_of_4.xlsx')
df_2025_2_44 = pd.read_excel('/content/2025-02-01_2025-02-28_part_4_of_4.xlsx')
df_2025_3_14 = pd.read_excel('/content/2025-03-01_2025-03-31_part_1_of_4.xlsx')
df_2025_3_24 = pd.read_excel('/content/2025-03-01_2025-03-31_part_2_of_4.xlsx')
df_2025_3_34 = pd.read_excel('/content/2025-03-01_2025-03-31_part_3_of_4.xlsx')
df_2025_3_44 = pd.read_excel('/content/2025-03-01_2025-03-31_part_4_of_4.xlsx')
df_2026_1_13 = pd.read_excel('/content/2026-01-01_2026-01-31_part_1_of_3.xlsx')
df_2026_1_23 = pd.read_excel('/content/2026-01-01_2026-01-31_part_2_of_3.xlsx')
df_2026_1_33 = pd.read_excel('/content/2026-01-01_2026-01-31_part_3_of_3.xlsx')
df_2026_2_13 = pd.read_excel('/content/2026-02-01_2026-02-28_part_1_of_3.xlsx')
df_2026_2_23 = pd.read_excel('/content/2026-02-01_2026-02-28_part_2_of_3.xlsx')
df_2026_2_33 = pd.read_excel('/content/2026-02-01_2026-02-28_part_3_of_3.xlsx')
df_2026_3_13 = pd.read_excel('/content/2026-03-01_2026-03-31_part_1_of_3.xlsx')
df_2026_3_23 = pd.read_excel('/content/2026-03-01_2026-03-31_part_2_of_3.xlsx')
df_2026_3_33 = pd.read_excel('/content/2026-03-01_2026-03-31_part_3_of_3.xlsx')

In [9]:
import pandas as pd

# เตรียมรายการสำหรับเก็บ DataFrame ที่ขึ้นต้นด้วย 'df_2024'
dfs_2024_prefix = []

# วนลูปผ่านพจนานุกรม dataframes เพื่อจัดกลุ่ม
for key, df in dataframes.items():
    if key.startswith('df_2024'):
        dfs_2024_prefix.append(df)

# รวม DataFrames ที่ขึ้นต้นด้วย 'df_2024'
if dfs_2024_prefix:
    df_2024 = pd.concat(dfs_2024_prefix, ignore_index=True)
    print(f"df_2024 สร้างแล้วด้วย {df_2024.shape[0]} แถว และ {df_2024.shape[1]} คอลัมน์")
else:
    print("ไม่พบข้อมูลสำหรับ DataFrame ที่ขึ้นต้นด้วย 'df_2024'")

df_2024 สร้างแล้วด้วย 4592 แถว และ 73 คอลัมน์

In [8]:
df_2024

,หมายเลขคำสั่งซื้อ,สถานะการสั่งซื้อ,Hot Listing,สถานะการคืนเงินหรือคืนสินค้า,ชื่อผู้ใช้ (ผู้ซื้อ),วันที่ทำการสั่งซื้อ,เวลาการชำระสินค้า,ช่องทางการชำระเงิน,ช่องทางการชำระเงิน (รายละเอียด),แผนการผ่อนชำระ,...,รหัสประจำสาขา,ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป,รายละเอียดที่อยู่,แขวง/ตำบล,เขต/อำเภอ.1,จังหวัด.1,รหัสไปรษณีย์.1,หมายเลขประจำตัวผู้เสียภาษี,หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี,อีเมลสำหรับรับใบกำกับภาษี
0,240103UWX9N588,สำเร็จแล้ว,N,NaN,bam_beebee,2024-01-03 12:44,2024-01-03 12:44,Mobile Banking,NaN,iBanking Payment V2 (SCB),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,240103UWX9N588,สำเร็จแล้ว,N,NaN,bam_beebee,2024-01-03 12:44,2024-01-03 12:44,Mobile Banking,NaN,iBanking Payment V2 (SCB),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,240103THAPRG1G,สำเร็จแล้ว,N,NaN,preorder_usa,2024-01-02 23:26,2024-01-02 23:26,บัตรเครดิต/บัตรเดบิต,NaN,Airpay Credit Card,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,240103THAPRG1G,สำเร็จแล้ว,N,NaN,preorder_usa,2024-01-02 23:26,2024-01-02 23:26,บัตรเครดิต/บัตรเดบิต,NaN,Airpay Credit Card,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,240102SRPHXTVH,สำเร็จแล้ว,N,NaN,mon_090mm,2024-01-02 16:05,2024-01-02 16:35,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4587,240228QDVYJ6BC,สำเร็จแล้ว,N,NaN,y6b22a2qdi,2024-02-28 14:40,2024-02-28 15:10,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4588,240228R0SMM799,สำเร็จแล้ว,N,NaN,gingkeaw33,2024-02-28 20:18,2024-02-28 20:18,SPayLater,Shopee Credit Down Payment,Shopee Credit x5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4589,240228QKHJUTKE,สำเร็จแล้ว,N,NaN,5tov371bpc,2024-02-28 16:21,2024-02-28 16:51,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4590,240229TCW7NHS5,สำเร็จแล้ว,N,NaN,nattikan555,2024-02-29 19:00,2024-02-29 19:00,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4591,240229TM43TS9Q,สำเร็จแล้ว,N,NaN,poppychon,2024-02-29 21:09,2024-02-29 21:09,SPayLater,Shopee Credit Down Payment,Shopee Credit x12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
import pandas as pd

# เตรียมรายการสำหรับเก็บ DataFrame ที่ขึ้นต้นด้วย 'df_2024'
dfs_2025_prefix = []

# วนลูปผ่านพจนานุกรม dataframes เพื่อจัดกลุ่ม
for key, df in dataframes.items():
    if key.startswith('df_2025'):
        dfs_2025_prefix.append(df)

# รวม DataFrames ที่ขึ้นต้นด้วย 'df_2024'
if dfs_2025_prefix:
    df_2025 = pd.concat(dfs_2025_prefix, ignore_index=True)
    print(f"df_2025 สร้างแล้วด้วย {df_2025.shape[0]} แถว และ {df_2025.shape[1]} คอลัมน์")
else:
    print("ไม่พบข้อมูลสำหรับ DataFrame ที่ขึ้นต้นด้วย 'df_2025'")

df_2025 สร้างแล้วด้วย 61391 แถว และ 73 คอลัมน์

In [11]:
df_2025

,หมายเลขคำสั่งซื้อ,สถานะการสั่งซื้อ,Hot Listing,สถานะการคืนเงินหรือคืนสินค้า,ชื่อผู้ใช้ (ผู้ซื้อ),วันที่ทำการสั่งซื้อ,เวลาการชำระสินค้า,ช่องทางการชำระเงิน,ช่องทางการชำระเงิน (รายละเอียด),แผนการผ่อนชำระ,...,รหัสประจำสาขา,ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป,รายละเอียดที่อยู่,แขวง/ตำบล,เขต/อำเภอ.1,จังหวัด.1,รหัสไปรษณีย์.1,หมายเลขประจำตัวผู้เสียภาษี,หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี,อีเมลสำหรับรับใบกำกับภาษี
0,250107SJBWUVWK,สำเร็จแล้ว,N,NaN,eyetanida,2025-01-06 23:05,2025-01-06 23:08,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,250107SJBWUVWK,สำเร็จแล้ว,N,NaN,eyetanida,2025-01-06 23:05,2025-01-06 23:08,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,250106SB9KPU3W,สำเร็จแล้ว,N,NaN,fbg2bln95t,2025-01-06 20:58,2025-01-06 20:58,ยอดเงิน ShopeePay,NaN,Airpay Wallet V2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,250106SB9KPU3W,สำเร็จแล้ว,N,NaN,fbg2bln95t,2025-01-06 20:58,2025-01-06 20:58,ยอดเงิน ShopeePay,NaN,Airpay Wallet V2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,250115GKMUWJ44,สำเร็จแล้ว,N,NaN,ecwce1rz0n,2025-01-14 23:20,2025-01-14 23:50,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61386,250131VWRB5PKB,สำเร็จแล้ว,N,NaN,amazingyes,2025-01-31 10:40,2025-01-31 19:52,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61387,250131VVPNHUHA,สำเร็จแล้ว,N,NaN,ntk9vnatb3,2025-01-31 10:21,2025-01-31 10:51,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61388,2501310GX0QK04,สำเร็จแล้ว,N,NaN,zg51s4fn7d,2025-01-31 17:23,2025-01-31 21:23,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61389,250130UFHMRMMG,สำเร็จแล้ว,N,NaN,kittiyaporn788,2025-01-30 20:53,2025-01-30 21:23,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61390,250131W2FUQ8RP,สำเร็จแล้ว,N,NaN,thepreciousm,2025-01-31 12:05,2025-02-01 11:39,ยอดเงิน ShopeePay,NaN,Airpay Wallet V2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
import pandas as pd

# เตรียมรายการสำหรับเก็บ DataFrame ที่ขึ้นต้นด้วย 'df_2024'
dfs_2026_prefix = []

# วนลูปผ่านพจนานุกรม dataframes เพื่อจัดกลุ่ม
for key, df in dataframes.items():
    if key.startswith('df_2026'):
        dfs_2026_prefix.append(df)

# รวม DataFrames ที่ขึ้นต้นด้วย 'df_2024'
if dfs_2026_prefix:
    df_2026 = pd.concat(dfs_2026_prefix, ignore_index=True)
    print(f"df_2026 สร้างแล้วด้วย {df_2026.shape[0]} แถว และ {df_2026.shape[1]} คอลัมน์")
else:
    print("ไม่พบข้อมูลสำหรับ DataFrame ที่ขึ้นต้นด้วย 'df_2026'")

df_2026 สร้างแล้วด้วย 52091 แถว และ 73 คอลัมน์

In [13]:
df_2026

,หมายเลขคำสั่งซื้อ,สถานะการสั่งซื้อ,Hot Listing,สถานะการคืนเงินหรือคืนสินค้า,ชื่อผู้ใช้ (ผู้ซื้อ),วันที่ทำการสั่งซื้อ,เวลาการชำระสินค้า,ช่องทางการชำระเงิน,ช่องทางการชำระเงิน (รายละเอียด),แผนการผ่อนชำระ,...,รหัสประจำสาขา,ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป,รายละเอียดที่อยู่,แขวง/ตำบล,เขต/อำเภอ.1,จังหวัด.1,รหัสไปรษณีย์.1,หมายเลขประจำตัวผู้เสียภาษี,หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี,อีเมลสำหรับรับใบกำกับภาษี
0,260107C77KBGYG,สำเร็จแล้ว,N,NaN,phon_1987,2026-01-07 00:35,2026-01-07 01:05,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,260119E1E905A5,สำเร็จแล้ว,N,NaN,asmah200536,2026-01-19 07:43,2026-01-19 08:13,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,260119E1E905A5,สำเร็จแล้ว,N,NaN,asmah200536,2026-01-19 07:43,2026-01-19 08:13,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,260119E1E905A5,สำเร็จแล้ว,N,NaN,asmah200536,2026-01-19 07:43,2026-01-19 08:13,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,260120H333KAX9,สำเร็จแล้ว,N,NaN,perfectskinn.th,2026-01-20 12:50,2026-01-20 12:52,SPayLater,Special SPayLater,Shopee Credit x5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52086,2603034XXXVKUY,สำเร็จแล้ว,N,NaN,nongnamo20,2026-03-03 00:11,2026-03-03 12:16,SPayLater,Special SPayLater,Shopee Credit x3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52087,2603035Q56CXCK,สำเร็จแล้ว,N,NaN,umaphon.au,2026-03-03 07:24,2026-03-03 07:25,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52088,2603035Q56CXCK,สำเร็จแล้ว,N,NaN,umaphon.au,2026-03-03 07:24,2026-03-03 07:25,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52089,2603036TE6EDA7,สำเร็จแล้ว,N,NaN,rgzed5wyo8,2026-03-03 17:55,2026-03-03 17:56,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52090,2603036TE6EDA7,สำเร็จแล้ว,N,NaN,rgzed5wyo8,2026-03-03 17:55,2026-03-03 17:56,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
import pandas as pd

# รวม DataFrames df_2024, df_2025, และ df_2026 เข้าด้วยกัน
# ตรวจสอบว่า DataFrames มีอยู่ก่อนที่จะทำการรวม

all_dfs_to_concat = []

if 'df_2024' in locals() and not df_2024.empty:
    all_dfs_to_concat.append(df_2024)
    print(f"df_2024 มี {df_2024.shape[0]} แถว")
else:
    print("ไม่พบ df_2024 หรือเป็น DataFrame ว่าง")

if 'df_2025' in locals() and not df_2025.empty:
    all_dfs_to_concat.append(df_2025)
    print(f"df_2025 มี {df_2025.shape[0]} แถว")
else:
    print("ไม่พบ df_2025 หรือเป็น DataFrame ว่าง")

if 'df_2026' in locals() and not df_2026.empty:
    all_dfs_to_concat.append(df_2026)
    print(f"df_2026 มี {df_2026.shape[0]} แถว")
else:
    print("ไม่พบ df_2026 หรือเป็น DataFrame ว่าง")

if all_dfs_to_concat:
    shopee = pd.concat(all_dfs_to_concat, ignore_index=True)
    print(f"\nDataFrame 'shopee' สร้างแล้วด้วย {shopee.shape[0]} แถว และ {shopee.shape[1]} คอลัมน์")
else:
    print("ไม่พบ DataFrame ที่จะนำมารวมกัน ไม่มี DataFrame 'shopee' ถูกสร้างขึ้น")

df_2024 มี 4592 แถว
df_2025 มี 61391 แถว
df_2026 มี 52091 แถว

DataFrame 'shopee' สร้างแล้วด้วย 118074 แถว และ 73 คอลัมน์

In [15]:
shopee

,หมายเลขคำสั่งซื้อ,สถานะการสั่งซื้อ,Hot Listing,สถานะการคืนเงินหรือคืนสินค้า,ชื่อผู้ใช้ (ผู้ซื้อ),วันที่ทำการสั่งซื้อ,เวลาการชำระสินค้า,ช่องทางการชำระเงิน,ช่องทางการชำระเงิน (รายละเอียด),แผนการผ่อนชำระ,...,รหัสประจำสาขา,ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป,รายละเอียดที่อยู่,แขวง/ตำบล,เขต/อำเภอ.1,จังหวัด.1,รหัสไปรษณีย์.1,หมายเลขประจำตัวผู้เสียภาษี,หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี,อีเมลสำหรับรับใบกำกับภาษี
0,240103UWX9N588,สำเร็จแล้ว,N,NaN,bam_beebee,2024-01-03 12:44,2024-01-03 12:44,Mobile Banking,NaN,iBanking Payment V2 (SCB),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,240103UWX9N588,สำเร็จแล้ว,N,NaN,bam_beebee,2024-01-03 12:44,2024-01-03 12:44,Mobile Banking,NaN,iBanking Payment V2 (SCB),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,240103THAPRG1G,สำเร็จแล้ว,N,NaN,preorder_usa,2024-01-02 23:26,2024-01-02 23:26,บัตรเครดิต/บัตรเดบิต,NaN,Airpay Credit Card,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,240103THAPRG1G,สำเร็จแล้ว,N,NaN,preorder_usa,2024-01-02 23:26,2024-01-02 23:26,บัตรเครดิต/บัตรเดบิต,NaN,Airpay Credit Card,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,240102SRPHXTVH,สำเร็จแล้ว,N,NaN,mon_090mm,2024-01-02 16:05,2024-01-02 16:35,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118069,2603034XXXVKUY,สำเร็จแล้ว,N,NaN,nongnamo20,2026-03-03 00:11,2026-03-03 12:16,SPayLater,Special SPayLater,Shopee Credit x3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118070,2603035Q56CXCK,สำเร็จแล้ว,N,NaN,umaphon.au,2026-03-03 07:24,2026-03-03 07:25,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118071,2603035Q56CXCK,สำเร็จแล้ว,N,NaN,umaphon.au,2026-03-03 07:24,2026-03-03 07:25,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118072,2603036TE6EDA7,สำเร็จแล้ว,N,NaN,rgzed5wyo8,2026-03-03 17:55,2026-03-03 17:56,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118073,2603036TE6EDA7,สำเร็จแล้ว,N,NaN,rgzed5wyo8,2026-03-03 17:55,2026-03-03 17:56,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN